
language: sh
sudo: required
matrix:
  include:
    - osx_image: xcode8.0
      os: osx
      sudo: required
    - osx_image: xcode7.1
      os: osx
      sudo: required
    - osx_image: xcode8.1
      sudo: required
      os: osx
    - os: linux
      sudo: required
      env:  ZSH_VERSION=5.2
    - os: linux,
      sudo: required
      env:  ZSH_VERSION=5.1

install:
    - ./bootstrap.travis.ci
script:
  - ./source.travis.ci
  - ./shellcheck.travis.ci

notifications:
  email: true
addons:
  apt:
    sources:
    - debian-sid    # Grab ShellCheck from the Debian repo
    packages:
    - shellcheck
branches:
  only:
    - master
