

function VmOpp(){
    vmrun
}


function git_init_gitignore(){
    echo "#----autogenerated gitignore----
.idea
*.iml
public/assets
.DS_Store
.ember.pid
node_modules/
bower_components/

/vendor/bundle
disabledServer/
/public/tests

#CocoaPods
Pods/
GeneratedDocumentation/
Carthage.checkout/
/.bundle

# Ignore the default SQLite database.
/db/*.sqlite3
/target
/log/*.log
/tmp
" >>| .gitignore

}

function git_setup(){
  git_init_gitignore;
  git init;
  git add .
  git commit -m "Initial commit"
}

function no_index_here(){
   touch .metadata_never_index;
}
