

function VmOpp(){
    vmrun
}


function git_init_gitignore(){
    echo "#----autogenerated gitignore----
.idea
*.iml
public/assets
.DS_Store
.ember.pid

/vendor/bundle
/public/tests

#CocoaPods
Pods/
GeneratedDocumentation/
Carthage.checkout/
/.bundle

# Ignore the default SQLite database.
/db/*.sqlite3
/target
/log/*.log
/tmp
" >>| .gitignore


}


function no_index_here(){
   touch .metadata_never_index;
}
