HOME_FOLDER=$(cd; pwd)

SCRIPTS_FOLDER="${HOME_FOLDER}/.zsh_scripts"
RUNNABLES_FOLDER="${SCRIPTS_FOLDER}/runnables"
JXA_FOLDER="${SCRIPTS_FOLDER}/JXA"
RUBY_FOLDER="${SCRIPTS_FOLDER}/ruby"
PROJECTS_FOLDER="${HOME_FOLDER}/Projects"
CONTRACT_PROJECTS_FOLDER="${PROJECTS_FOLDER}/Contract"
WORK_PROJECTS_FOLDER="${PROJECTS_FOLDER}/Work"
    MY_PROJECTS_FOLDER="${PROJECTS_FOLDER}/Mine"
SETUP_SCRIPT_FOLDER="${MY_PROJECTS_FOLDER}/setup_script/"
SETUP_SCRIPT="${SETUP_SCRIPT_FOLDER}/setup.sh"
CDN_FOLDER="${MY_PROJECTS_FOLDER}/cdn"


GITHUB_HTTP_URL="https://github.com/"
GITHUB_HANDLE="joedaniels29"
GITHB_HTTP_URL_ME="${GITHUB_HTTP_URL}/${GITHUB_HANDLE}"

GITHUB_SSH_HOST='git@github.com'
GITHB_SSH_ROOT="${GITHUB_SSH_HOST}:${GITHUB_HANDLE}"


if [[ "$(uname)" == "Darwin" ]]; then
    WORK_PROJECTS_FOLDER="${PROJECTS_FOLDER}/Work"
elif [ "$(expr substr $(uname -s) 1 5)" = "Linux" ]; then
    WORK_PROJECTS_FOLDER="${HOME_FOLDER}/Projects"
fi
