tf_activate(){
    source ~/Projects/Mine/tensorflow/bin/activate
}

tf_version(){
    tf_activate
     python -c 'import tensorflow as tf; print(tf.__version__)'
}

tf_syntax_net(){
    tf_checkout
    cd models/syntaxnet/tensorflow
    ./configure
     cd ..
     bazel test --linkopt=-headerpad_max_install_names \
        syntaxnet/... util/utf8/...
}

tf_checkout(){
    tf_activate
    cd $MY_PROJECTS_FOLDER;
    rm -rf ./models
    git clone --recursive https://github.com/tensorflow/models.git
}

tf_im2txt(){
    tf_activate
# Directory containing model checkpoints.
CHECKPOINT_DIR="${HOME}/Downloads/model.ckpt-2000000"

# Vocabulary file generated by the preprocessing script.
VOCAB_FILE="${HOME}/Downloads/word_counts.txt"

# JPEG image file to caption.
IMAGE_FILE="${HOME}/Projects/Mine/models/im2txt/g3doc/COCO_val2014_000000224477.jpg"

# Build the inference binary.
bazel build -c opt im2txt/run_inference

# Ignore GPU devices (only necessary if your GPU is currently memory
# constrained, for example, by running the training script).
export CUDA_VISIBLE_DEVICES=""

# Run inference to generate captions.
bazel-bin/im2txt/run_inference \
  --checkpoint_path=${CHECKPOINT_DIR} \
  --vocab_file=${VOCAB_FILE} \
  --input_files=${IMAGE_FILE}
}
